const pizzas = [
    { id: 1,
    nombre: "Muzzarella",
    ingredientes: ["muzzarella", "salsa", "aceitunas"],
    precio: 800,
    imagen: "muzzarellaLista.jpg"},
    { id: 2,
    nombre: "Hawaiana",
    ingredientes: ["muzzarella", "salsa", "anana", "jamon", "extra queso"],
    precio: 1400, 
    imagen: "hawaianaLista.jpg"},
    { id: 3,
    nombre: "Deluxe",
    ingredientes: ["muzzarella", "salsa", "peperoni", "salchichas", "pimientos", "cebollas", "champignones"],
    precio: 1500, 
    imagen: "deluxeLista.jpg"},
    { id: 4,
    nombre: "Americana",
    ingredientes: ["muzzarella", "salsa", "jamon", "aceitunas"],
    precio: 980, 
    imagen: "americanaLista.jpg"},
    { id: 5,
    nombre: "Hot chicken",
    ingredientes: ["muzzarella", "salsa", "pollo", "pimientos", "champignones"],
    precio: 1500, 
    imagen: "hotChickenLista.jpg"},
    { id: 6,
    nombre: "Super queso",
    ingredientes: ["muzzarella", "4 quesos", "aceitunas", "cebolla"],
    precio: 1200, 
    imagen: "superQuesoLista.jpg"},
    { id: 7,
    nombre: "Roquefort",
    ingredientes: ["muzzarella", "salsa", "roquefort", "jamon"],
    precio: 1100, 
    imagen: "roquefortLista.jpg"},
    ];